// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

// Protobuf Java Version: 4.26.0
package com.server.newhopeserver.proto;

public interface protoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:msg.protoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int64 coefs = 1;</code>
   * @return A list containing the coefs.
   */
  java.util.List<java.lang.Long> getCoefsList();
  /**
   * <code>repeated int64 coefs = 1;</code>
   * @return The count of coefs.
   */
  int getCoefsCount();
  /**
   * <code>repeated int64 coefs = 1;</code>
   * @param index The index of the element to return.
   * @return The coefs at the given index.
   */
  long getCoefs(int index);

  /**
   * <code>bytes seed = 2;</code>
   * @return The seed.
   */
  com.google.protobuf.ByteString getSeed();
}
